apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2048
  labels:
    app.kubernetes.io/name: game2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: game2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game2048
    spec:
      containers:
        - name: 2048game
          image: "alexwhen/docker-2048:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

