apiVersion: v1
kind: Service
metadata:
  name: game2048
  labels:
    app.kubernetes.io/name: game2048
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: game2048
